apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "check.fullname" . }}
  labels:
    {{- include "check.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi